# Generated by Django 4.2.1 on 2023-05-25 11:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('message', models.TextField()),
                ('filters', models.JSONField(default=dict)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('time_interval_start', models.TimeField(default=datetime.time(0, 0))),
                ('time_interval_end', models.TimeField(default=datetime.time(23, 59, 59, 999999))),
            ],
            options={
                'db_table': 'mailing',
            },
        ),
        migrations.CreateModel(
            name='MailingTask',
            fields=[
                ('mailing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mailing_task', serialize=False, to='mailing.mailing')),
                ('task', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mailing_task',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='clients.client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailing.mailing')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.AddIndex(
            model_name='mailing',
            index=models.Index(fields=['start_date'], name='mailing_start_d_3c5a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status'], name='message_status_fbc084_idx'),
        ),
    ]
