services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A main worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  beat:
    build: .
    command: celery -A main beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  main:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis