# Generated by Django 4.2.1 on 2023-05-25 12:17

from django.db import migrations


def create_daily_report_periodic_task(apps, schema_editor):
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute='59',
        hour='23',
        day_of_week='*',
        day_of_month='*',
        month_of_year='*',
    )
    PeriodicTask.objects.create(
        crontab=schedule,
        name='Daily Mailing Report',
        task='user_notification.tasks.send_daily_mailing_report',
    )


def delete_daily_report_periodic_task(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    PeriodicTask.objects.filter(
        name='Daily Mailing Report', task='user_notification.tasks.send_daily_mailing_report'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user_notification', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_daily_report_periodic_task, migrations.RunPython.noop)
    ]
